/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.musicranking;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;

import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Anupat
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FileNameLable = new javax.swing.JLabel();
        ChooseBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        Name1 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Name2 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        Name3 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        Name4 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        Name5 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        Name6 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        Name7 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        Name8 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        Name9 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        Name10 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        View1 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        View2 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        View3 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        View4 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        View7 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        View8 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        View5 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        View6 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        View9 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        View10 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        savedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jLabel1.setText("Music Ranking");

        FileNameLable.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        FileNameLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        ChooseBTN.setFont(new java.awt.Font("Angsana New", 1, 18)); // NOI18N
        ChooseBTN.setText("Choose File");
        ChooseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rank");

        jLabel3.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");

        jLabel9.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");

        jLabel10.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("6");

        jLabel11.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7");

        jLabel12.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8");

        jLabel13.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("9");

        jLabel14.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("10");

        Name1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name1.setText("#");

        Name2.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name2.setText("#");

        Name3.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name3.setText("#");

        Name4.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name4.setText("#");

        Name5.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name5.setText("#");

        Name6.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name6.setText("#");

        Name7.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name7.setText("#");

        Name8.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name8.setText("#");

        Name9.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name9.setText("#");

        Name10.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        Name10.setText("#");

        View1.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View1.setText("#");

        View2.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View2.setText("#");

        View3.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View3.setText("#");

        View4.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View4.setText("#");

        View7.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View7.setText("#");

        View8.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View8.setText("#");

        View5.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View5.setText("#");

        View6.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View6.setText("#");

        View9.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View9.setText("#");

        View10.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        View10.setText("#");

        savedLabel.setFont(new java.awt.Font("Angsana New", 3, 24)); // NOI18N
        savedLabel.setForeground(new java.awt.Color(0, 204, 51));
        savedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(127, 127, 127))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(FileNameLable, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(ChooseBTN)
                                                .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(savedLabel,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel7,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel8,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel9,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel11,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel12,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel13,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jLabel14,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator3)
                                                                        .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                54, Short.MAX_VALUE)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                        jSeparator4,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator5,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator6,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator7,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator8,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator9,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator10,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator11,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(
                                                                                                        jSeparator12,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                        .addGap(1, 1, 1)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSeparator1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        164,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 20, Short.MAX_VALUE))
                                                                        .addComponent(Name1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator13)
                                                                        .addComponent(Name2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator14)
                                                                        .addComponent(Name3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator15)
                                                                        .addComponent(Name4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator16)
                                                                        .addComponent(Name5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator17)
                                                                        .addComponent(Name6,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator18)
                                                                        .addComponent(Name7,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator19)
                                                                        .addComponent(Name8,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator20)
                                                                        .addComponent(Name9,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator21)
                                                                        .addComponent(Name10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator22))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jSeparator2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 9,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                111,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(View1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator23)
                                                                        .addComponent(View2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator24)
                                                                        .addComponent(View3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator25)
                                                                        .addComponent(View4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator26)
                                                                        .addComponent(View5,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator29)
                                                                        .addComponent(View6,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator30)
                                                                        .addComponent(View7,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator27)
                                                                        .addComponent(View8,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator28)
                                                                        .addComponent(View9,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                128, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator31)
                                                                        .addComponent(View10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jSeparator32))))
                                                .addGap(10, 10, 10)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FileNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ChooseBTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(savedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2)
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel6)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel7)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel8)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel9)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel10)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel11)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator9,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel12)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel13)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator11,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0)
                                                                .addComponent(jLabel14)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jSeparator12,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(View1)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator23,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(Name1)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator13,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(Name2)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator14,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name3)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator15,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name4)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator16,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name5)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator17,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name6)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator18,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name7)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator19,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name8)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator20,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name9)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator21,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(Name10)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator22,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(View2)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator24,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View3)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator25,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View4)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator26,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View5)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator29,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View6)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator30,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View7)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator27,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View8)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator28,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(View9)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator31,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, 0)
                                                                                .addComponent(View10)
                                                                                .addGap(2, 2, 2)
                                                                                .addComponent(jSeparator32,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        FileNameLable.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // สร้าง JFileChooser เพื่อเปิดหน้าต่างให้ผู้ใช้เลือกไฟล์
        JFileChooser chooser = new JFileChooser();
        // กำหนด filter เฉพาะไฟล์นามสกุล .csv เพื่อเลือกไฟล์ csv เท่านั้น
        FileFilter filter = new FileNameExtensionFilter("CSV files", "csv");
        chooser.setFileFilter(filter);
        // แสดงหน้าต่างเลือกไฟล์ และรับค่าการเลือกไฟล์ที่ผู้ใช้ทำ
        // ในกรณีนี้ควรเลือกไฟล์ .csv และมีข้อมูลเป็นภาษาอังกฤษเท่านั้น
        int returnVal = chooser.showOpenDialog(this);

        // ถ้าผู้ใช้เลือกไฟล์เรียบร้อย
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // ดึงข้อมูลของไฟล์ที่ผู้ใช้เลือก
            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();

            // เพื่อให้แสดงเฉพาะชื่อไฟล์
            String[] ps = path.split("\\\\");
            String FileName = ps[ps.length - 1];

            // แสดงชื่อไฟล์ที่เลือกใน Label
            FileNameLable.setText(FileName);

            // อ่านข้อมูลจากไฟล์ csv และแสดง Top 10 Music ที่มีการ View Count มากที่สุด
            List<MusicData> musicList = new ArrayList<>();
            try (BufferedReader reader = new BufferedReader(new FileReader(path))) {
                String line;
                boolean headerSkipped = false;
                while ((line = reader.readLine()) != null) {
                    // ข้าม header ไฟล์ csv
                    if (!headerSkipped) {
                        headerSkipped = true;
                        continue;
                    }
                    // แยกข้อมูลของแต่ละ column ด้วย delimiter ","
                    String[] parts = line.split(",");
                    // ถ้าไม่ใช่ข้อมูลที่มี 2 column ให้ข้ามไปเลย
                    if (parts.length != 2) {
                        continue;
                    }
                    // สร้าง MusicData object และกำหนดชื่อและจำนวนการเข้าชม
                    MusicData musicData = new MusicData();
                    musicData.setName(parts[0]);
                    musicData.setViewCount(Integer.parseInt(parts[1]));
                    musicList.add(musicData);
                }

                // เรียงลำดับตามจำนวนการเข้าชม และเลือก Top 10 Music
                Collections.sort(musicList, (a, b) -> b.getViewCount() - a.getViewCount());
                List<MusicData> top10MusicList = musicList.subList(0, Math.min(musicList.size(), 10));

                // สร้าง NumberFormat เพื่อแสดงจำนวนเป็นรูปแบบของตัวเลข
                NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);

                // แสดงข้อมูล Top 10 Music ที่มีจำนวนการเข้าชมมากที่สุด
                Name1.setText(top10MusicList.get(0).getName());
                View1.setText(numberFormat.format(top10MusicList.get(0).getViewCount()));
                Name2.setText(top10MusicList.get(1).getName());
                View2.setText(numberFormat.format(top10MusicList.get(1).getViewCount()));
                Name3.setText(top10MusicList.get(2).getName());
                View3.setText(numberFormat.format(top10MusicList.get(2).getViewCount()));
                Name4.setText(top10MusicList.get(3).getName());
                View4.setText(numberFormat.format(top10MusicList.get(3).getViewCount()));
                Name5.setText(top10MusicList.get(4).getName());
                View5.setText(numberFormat.format(top10MusicList.get(4).getViewCount()));
                Name6.setText(top10MusicList.get(5).getName());
                View6.setText(numberFormat.format(top10MusicList.get(5).getViewCount()));
                Name7.setText(top10MusicList.get(6).getName());
                View7.setText(numberFormat.format(top10MusicList.get(6).getViewCount()));
                Name8.setText(top10MusicList.get(7).getName());
                View8.setText(numberFormat.format(top10MusicList.get(7).getViewCount()));
                Name9.setText(top10MusicList.get(8).getName());
                View9.setText(numberFormat.format(top10MusicList.get(8).getViewCount()));
                Name10.setText(top10MusicList.get(9).getName());
                View10.setText(numberFormat.format(top10MusicList.get(9).getViewCount()));

                // สร้างไฟล์ ranking.txt และเขียนข้อมูล Top 10 Music ที่มีจำนวนการเข้าชมมากที่สุด

                // สร้างไฟล์ ranking.txt ที่อยู่ในโฟลเดอร์ของโปรเจค
                PrintWriter writer = new PrintWriter("ranking.txt");

                // เขียนหัวข้อของแต่ละ column
                writer.println(String.format("%-30s %10s", "Music Name", "View Count"));

                // เขียนข้อมูลของแต่ละแถว
                for (int i = 0; i < top10MusicList.size(); i++) {
                    MusicData music = top10MusicList.get(i);
                    String row = String.format("%-30s %,10d", music.getName(), music.getViewCount());
                    writer.println(String.format("%-2d. %s", i + 1, row));
                }

                // แสดงข้อความเตือนเมื่อสร้างไฟล์ ranking.txt สำเร็จ
                System.out.println("ranking.txt file created successfully");
                // ตั้งค่าข้อความและสีของ savedLabel
                savedLabel.setForeground(new Color(0, 180, 0));
                savedLabel.setText("ranking.txt file created at the project folder successfully");
                // ปิดไฟล์
                writer.close();

            } catch (Exception e) {
                // แสดงข้อความเตือนเมื่อไม่สามารถอ่านไฟล์ได้
                // ตั้งค่าข้อความและสีของ savedLabel
                savedLabel.setForeground(Color.RED);
                savedLabel.setText("Failed to read the file. Please try again.");
            }
        }

    }// GEN-LAST:event_ChooseBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseBTN;
    private javax.swing.JLabel FileNameLable;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name10;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Name7;
    private javax.swing.JLabel Name8;
    private javax.swing.JLabel Name9;
    private javax.swing.JLabel View1;
    private javax.swing.JLabel View10;
    private javax.swing.JLabel View2;
    private javax.swing.JLabel View3;
    private javax.swing.JLabel View4;
    private javax.swing.JLabel View5;
    private javax.swing.JLabel View6;
    private javax.swing.JLabel View7;
    private javax.swing.JLabel View8;
    private javax.swing.JLabel View9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel savedLabel;
    // End of variables declaration//GEN-END:variables
}
